import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { cp, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, it } from "node:test";
import { promisify } from "node:util";
import { generateIcons } from "../src/index.ts";

const execFileAsync = promisify(execFile);
const FIXTURES_DIR = path.resolve(import.meta.dirname, "fixtures/icons");
const CLI_PATH = path.resolve(import.meta.dirname, "../src/cli.ts");

async function createTsProject(tmpDir: string, sourceFiles: Record<string, string>): Promise<void> {
  await writeFile(
    path.join(tmpDir, "tsconfig.json"),
    JSON.stringify({
      compilerOptions: {
        target: "ESNext",
        module: "ESNext",
        moduleResolution: "Bundler",
        strict: true,
        noEmit: true,
      },
      include: ["./**/*.ts", "./**/*.tsx"],
    }),
  );
  for (const [name, content] of Object.entries(sourceFiles)) {
    const filePath = path.join(tmpDir, name);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, content);
  }
}

describe("icons-unused CLI", () => {
  let tmpDir: string;
  let inputDir: string;
  let outputDir: string;
  let outputFile: string;
  let typesFile: string;

  beforeEach(async () => {
    tmpDir = await mkdtemp(path.join(tmpdir(), "icons-cli-test-"));
    inputDir = path.join(tmpDir, "icons");
    outputDir = path.join(tmpDir, "output");
    outputFile = path.join(outputDir, "sprite.svg");
    typesFile = path.join(outputDir, "icons.ts");
    await cp(FIXTURES_DIR, inputDir, { recursive: true });
    await generateIcons({ inputDir, outputFile, typesFile, cwd: tmpDir });
  });

  afterEach(async () => {
    await rm(tmpDir, { recursive: true, force: true });
  });

  const runCli = (extraArgs: string[] = []) =>
    execFileAsync("node", [CLI_PATH, "--types-file", typesFile, "--cwd", tmpDir, ...extraArgs]);

  const singleCircleProject = () =>
    createTsProject(tmpDir, {
      "app/component.ts": `
        import type { IconName } from "../output/icons";
        const icon: IconName = "Circle";
      `,
    });

  it("reports unused icons", async () => {
    await singleCircleProject();

    const { stdout } = await runCli();
    assert.ok(stdout.includes("Unused icons"), "should report unused icons");
    assert.ok(!stdout.includes("- Circle"), "Circle should not be listed as unused");
    assert.ok(stdout.includes("Multi"), "Multi should be listed as unused");
  });

  it("reports all icons used", async () => {
    await createTsProject(tmpDir, {
      "app/component.ts": `
        import type { IconName } from "../output/icons";
        const icons: IconName[] = ["Circle", "Empty", "Multi", "Namespace", "Polygon", "Version", "Width"];
      `,
    });

    const { stdout } = await runCli();
    assert.ok(stdout.includes("All icons are used"), "should report all icons used");
  });

  it("exits with code 1 when --error is set and icons are unused", async () => {
    await singleCircleProject();

    try {
      await runCli(["--error"]);
      assert.fail("should have exited with code 1");
    } catch (err: any) {
      assert.strictEqual(err.code, 1);
      assert.ok(err.stdout.includes("Unused icons"), "should report unused icons on error exit");
    }
  });

  it("exits with code 0 when --error is set and all icons are used", async () => {
    await createTsProject(tmpDir, {
      "app/component.ts": `
        import type { IconName } from "../output/icons";
        const icons: IconName[] = ["Circle", "Empty", "Multi", "Namespace", "Polygon", "Version", "Width"];
      `,
    });

    const { stdout } = await runCli(["--error"]);
    assert.ok(stdout.includes("All icons are used"), "should report all icons used");
  });

  it("exits with code 2 when --types-file is missing", async () => {
    try {
      await execFileAsync("node", [CLI_PATH]);
      assert.fail("should have exited with code 2");
    } catch (err: any) {
      assert.strictEqual(err.code, 2);
      assert.ok(err.stderr.includes("Usage:"), "should print usage on missing args");
    }
  });

  it("does not false-positive on untyped string literals", async () => {
    await createTsProject(tmpDir, {
      "app/unrelated.ts": `
        const label = "Circle";
        const description = "This is a Multi-line thing";
      `,
    });

    const { stdout } = await runCli();
    assert.ok(stdout.includes("Unused icons"), "should report unused icons");
    assert.ok(stdout.includes("7 of 7"), "all 7 icons should be unused");
  });

  it("parses types file with single-quoted icon names", async () => {
    // Simulate a formatter (e.g., Prettier with singleQuote: true) rewriting the types file
    const singleQuoteTypes = [
      "// This file is generated by icon spritesheet generator",
      "",
      "export const iconNames = [",
      "  'Circle',",
      "  'Empty',",
      "  'Multi',",
      "  'Namespace',",
      "  'Polygon',",
      "  'Version',",
      "  'Width',",
      "] as const",
      "",
      "export type IconName = typeof iconNames[number]",
      "",
    ].join("\n");
    await writeFile(typesFile, singleQuoteTypes);

    await singleCircleProject();

    const { stdout } = await runCli();
    assert.ok(stdout.includes("Unused icons"), "should report unused icons");
    assert.ok(!stdout.includes("- Circle"), "Circle should not be listed as unused");
    assert.ok(stdout.includes("6 of 7"), "6 of 7 icons should be unused");
  });

  it("detects icons used via template literals in typed positions", async () => {
    await createTsProject(tmpDir, {
      "app/flags.ts": `
        import type { IconName } from "../output/icons";
        type Suffix = "ircle" | "olygon";
        declare const s: Suffix;
        const icon: IconName = \`C\${s}\`;
      `,
    });

    const { stdout } = await runCli();
    assert.ok(stdout.includes("Unused icons"), "should report unused icons");
    assert.ok(!stdout.includes("- Circle"), "Circle should not be listed as unused");
    assert.ok(stdout.includes("Multi"), "Multi should be listed as unused");
  });
});
