// This file is generated by icon spritesheet generator

export const iconNames = ["Circle", "Empty", "Multi", "Namespace", "Polygon", "Version", "Width"] as const

export type IconName = (typeof iconNames)[number]
